import { Chip, Tooltip } from '@mui/material';
import { AutoAwesome, SmartToy } from '@mui/icons-material';

/**
 * AI Generated Badge
 * Shows that content was generated by AI
 */
const AIGeneratedBadge = ({ 
  size = "small", // "small", "medium"
  variant = "chip", // "chip", "icon"
  showTooltip = true 
}) => {
  const content = variant === "icon" ? (
    <SmartToy 
      sx={{ 
        fontSize: size === "small" ? 18 : 24,
        color: 'primary.main',
        animation: 'pulse 2s infinite',
        '@keyframes pulse': {
          '0%, 100%': { opacity: 0.8 },
          '50%': { opacity: 1 },
        }
      }} 
    />
  ) : (
    <Chip
      icon={<AutoAwesome sx={{ fontSize: size === "small" ? 14 : 18 }} />}
      label={size === "small" ? "AI" : "AI Generated"}
      size={size}
      sx={{
        background: 'linear-gradient(90deg, rgba(102, 126, 234, 0.15), rgba(118, 75, 162, 0.15))',
        border: '1px solid',
        borderColor: 'primary.light',
        color: 'primary.main',
        fontWeight: 600,
        fontSize: size === "small" ? '0.7rem' : '0.8rem',
        '& .MuiChip-icon': {
          color: 'primary.main',
        }
      }}
    />
  );

  if (showTooltip) {
    return (
      <Tooltip 
        title="This content was dynamically generated by AI specifically for you"
        arrow
      >
        {content}
      </Tooltip>
    );
  }

  return content;
};

export default AIGeneratedBadge;
