"""Add curriculum framework models

Revision ID: 04d79400632d
Revises: 91f1dedc3298
Create Date: 2025-10-19 15:25:33.643899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d79400632d'
down_revision = '91f1dedc3298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('level_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vocabulary_range_min', sa.Integer(), nullable=True),
    sa.Column('vocabulary_range_max', sa.Integer(), nullable=True),
    sa.Column('grammar_concepts', sa.JSON(), nullable=True),
    sa.Column('functional_skills', sa.JSON(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('prerequisite_level_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prerequisite_level_id'], ['curriculum_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cefr_level')
    )
    op.create_table('learning_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('curriculum_level_id', sa.Integer(), nullable=False),
    sa.Column('skill_domain', sa.String(length=50), nullable=False),
    sa.Column('concept_name', sa.String(length=200), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('activity_templates', sa.JSON(), nullable=True),
    sa.Column('example_content', sa.JSON(), nullable=True),
    sa.Column('difficulty_range_min', sa.Float(), nullable=True),
    sa.Column('difficulty_range_max', sa.Float(), nullable=True),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('mastery_threshold', sa.Float(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_level_id'], ['curriculum_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('node_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mastery_level', sa.Float(), nullable=True),
    sa.Column('first_attempt_date', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('mastery_date', sa.DateTime(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('activities_completed', sa.Integer(), nullable=True),
    sa.Column('mistakes_made', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'node_id', name='unique_user_node')
    )
    op.create_table('user_learning_path_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.String(length=2), nullable=False),
    sa.Column('current_node_id', sa.String(length=100), nullable=True),
    sa.Column('target_level', sa.String(length=2), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('learning_style', sa.String(length=50), nullable=True),
    sa.Column('preferred_pace', sa.String(length=20), nullable=True),
    sa.Column('preferred_session_length', sa.Integer(), nullable=True),
    sa.Column('skill_priorities', sa.JSON(), nullable=True),
    sa.Column('weak_areas', sa.JSON(), nullable=True),
    sa.Column('strong_areas', sa.JSON(), nullable=True),
    sa.Column('current_focus_skill', sa.String(length=50), nullable=True),
    sa.Column('nodes_completed', sa.Integer(), nullable=True),
    sa.Column('nodes_in_progress', sa.Integer(), nullable=True),
    sa.Column('nodes_mastered', sa.Integer(), nullable=True),
    sa.Column('learning_velocity', sa.Float(), nullable=True),
    sa.Column('average_accuracy', sa.Float(), nullable=True),
    sa.Column('time_invested_hours', sa.Float(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.Column('longest_streak_days', sa.Integer(), nullable=True),
    sa.Column('current_streak_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_learning_path_progress')
    op.drop_table('node_completions')
    op.drop_table('learning_nodes')
    op.drop_table('curriculum_levels')
    # ### end Alembic commands ###
