"""Add onboarding workflow and mastery tracking fields

Revision ID: 135f40a5c2cc
Revises: 76dfc0989a3b
Create Date: 2025-10-01 15:47:39.474154

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "135f40a5c2cc"
down_revision = "76dfc0989a3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "milestones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("milestone_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("telugu_title", sa.String(length=200), nullable=True),
        sa.Column("telugu_description", sa.Text(), nullable=True),
        sa.Column("achieved_at", sa.DateTime(), nullable=False),
        sa.Column("milestone_data", sa.JSON(), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("points_awarded", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lesson_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("activity_log_id", sa.Integer(), nullable=False),
        sa.Column("learning_path_id", sa.Integer(), nullable=True),
        sa.Column("performance_score", sa.Float(), nullable=True),
        sa.Column("strengths", sa.JSON(), nullable=True),
        sa.Column("weaknesses", sa.JSON(), nullable=True),
        sa.Column("feedback_english", sa.Text(), nullable=True),
        sa.Column("feedback_telugu", sa.Text(), nullable=True),
        sa.Column("next_lesson_recommendation", sa.JSON(), nullable=True),
        sa.Column("difficulty_adjustment", sa.String(length=20), nullable=True),
        sa.Column("focus_areas", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("ai_model_used", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_log_id"],
            ["user_activity_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learning_path_id"],
            ["learning_paths.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mastery_metrics", sa.JSON(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("onboarding_completed", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("needs_initial_assessment", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("assessment_taken_at", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("current_learning_phase", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(
            sa.Column("initial_assessment_id", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("initial_assessment_id")
        batch_op.drop_column("current_learning_phase")
        batch_op.drop_column("assessment_taken_at")
        batch_op.drop_column("needs_initial_assessment")
        batch_op.drop_column("onboarding_completed")

    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_column("mastery_metrics")

    op.drop_table("lesson_reviews")
    op.drop_table("milestones")
    # ### end Alembic commands ###
