"""Add missing fields to learning_paths table

Revision ID: 1b65a59f882b
Revises: c3775b52af82
Create Date: 2025-09-23 18:08:16.736931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b65a59f882b'
down_revision = 'c3775b52af82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_learning_paths',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'learning_path_id')
    )
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estimated_duration_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prerequisites', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('learning_objectives', sa.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f('learning_paths_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('completion_percentage')
        batch_op.drop_column('user_id')
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('completion_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('learning_paths_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('learning_objectives')
        batch_op.drop_column('prerequisites')
        batch_op.drop_column('estimated_duration_hours')
        batch_op.drop_column('category')

    op.drop_table('user_learning_paths')
    # ### end Alembic commands ###
