"""Add user preferences and profile bio fields

Revision ID: 4e9b68a25330
Revises: 4ce1b84d4079
Create Date: 2025-09-23 16:35:16.576022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9b68a25330'
down_revision = '4ce1b84d4079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('learning_goals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notification_preferences', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notification_preferences')
        batch_op.drop_column('learning_goals')
        batch_op.drop_column('timezone')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
