"""Add privacy_settings column to users table

Revision ID: 88912834fbdb
Revises: c1f03b24c624
Create Date: 2025-09-24 15:59:31.284336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88912834fbdb'
down_revision = 'c1f03b24c624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_settings', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('privacy_settings')

    # ### end Alembic commands ###
