"""Initial migration for all tables

Revision ID: 8f31f44cb5a8
Revises: b4d09671e539
Create Date: 2025-10-09 23:27:57.041616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f31f44cb5a8'
down_revision = 'b4d09671e539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('default_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('estimated_duration_days', sa.Integer(), nullable=True),
    sa.Column('criteria', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('points_reward', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('level_progressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_level', sa.String(length=50), nullable=True),
    sa.Column('to_level', sa.String(length=50), nullable=True),
    sa.Column('level_number', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('requirements_met', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_text', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=True),
    sa.Column('email', sa.Boolean(), nullable=True),
    sa.Column('push', sa.Boolean(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['notification_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_reminder_enabled', sa.Boolean(), nullable=True),
    sa.Column('daily_reminder_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('streak_alerts', sa.Boolean(), nullable=True),
    sa.Column('achievement_notifications', sa.Boolean(), nullable=True),
    sa.Column('new_content_notifications', sa.Boolean(), nullable=True),
    sa.Column('personalized_tips', sa.Boolean(), nullable=True),
    sa.Column('learning_path_updates', sa.Boolean(), nullable=True),
    sa.Column('in_app_notifications', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('weekend_reminders', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('achievement_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('criteria', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('current_progress', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('badge_earned_id', sa.Integer(), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('milestones_completed', sa.Integer(), nullable=True),
    sa.Column('milestones_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_earned_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['goal_type_id'], ['goal_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('certificate_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('certificate_number', sa.String(length=50), nullable=True),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('level_achieved', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('skills_mastered', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('verification_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['user_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('telugu_translation', sa.Text(), nullable=True),
    sa.Column('grammar_explanation', sa.Text(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_learning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('image_format', sa.String(length=10), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('analysis_status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('identified_objects', sa.JSON(), nullable=True),
    sa.Column('total_objects_found', sa.Integer(), nullable=True),
    sa.Column('objects_saved_to_vocabulary', sa.JSON(), nullable=True),
    sa.Column('flashcard_session_created', sa.Boolean(), nullable=True),
    sa.Column('flashcard_session_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_from_device', sa.String(length=50), nullable=True),
    sa.Column('is_camera_capture', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flashcard_session_id'], ['learning_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_object_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_learning_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_word_id', sa.Integer(), nullable=False),
    sa.Column('object_index', sa.Integer(), nullable=True),
    sa.Column('object_name_english', sa.String(length=200), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_learning_id'], ['image_learning.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_word_id'], ['vocabulary_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('current_chapter_id', sa.Integer(), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('completed_chapters', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.Column('completed_activities', sa.Integer(), nullable=True),
    sa.Column('total_time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_time_remaining_minutes', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('quiz_accuracy', sa.Float(), nullable=True),
    sa.Column('writing_score', sa.Float(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('badges_earned', sa.JSON(), nullable=True),
    sa.Column('certificate_issued', sa.Boolean(), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('difficulty_adjustments', sa.JSON(), nullable=True),
    sa.Column('recommended_next_activities', sa.JSON(), nullable=True),
    sa.Column('enrollment_metadata', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'learning_path_id', name='unique_user_learning_path')
    )
    op.create_table('chapter_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_unlocked', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.Column('completed_activities', sa.Integer(), nullable=True),
    sa.Column('current_activity_index', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['user_enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'chapter_id', name='unique_enrollment_chapter')
    )
    op.create_table('path_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('completion_time_days', sa.Integer(), nullable=True),
    sa.Column('total_points_earned', sa.Integer(), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('certificate_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['user_enrollments.id'], ),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number'),
    sa.UniqueConstraint('enrollment_id')
    )
    op.create_table('activity_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_progress_id', sa.Integer(), nullable=False),
    sa.Column('learning_session_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_unlocked', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_progress_id'], ['chapter_progress.id'], ),
    sa.ForeignKeyConstraint(['learning_session_id'], ['learning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_progress_id', 'learning_session_id', name='unique_chapter_activity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_progress')
    op.drop_table('path_certificates')
    op.drop_table('chapter_progress')
    op.drop_table('user_enrollments')
    op.drop_table('image_object_vocabulary')
    op.drop_table('image_learning')
    op.drop_table('chat_messages')
    op.drop_table('certificates')
    op.drop_table('achievement_goals')
    op.drop_table('user_notification_settings')
    op.drop_table('notifications')
    op.drop_table('level_progressions')
    op.drop_table('goal_types')
    op.drop_table('chat_conversations')
    op.drop_table('notification_types')
    # ### end Alembic commands ###
