"""Add user tracking tables

Revision ID: 91f1dedc3298
Revises: 8f31f44cb5a8
Create Date: 2025-10-17 20:05:02.220272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f1dedc3298'
down_revision = '8f31f44cb5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_content_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('content_format', sa.String(length=20), nullable=True),
    sa.Column('provider_used', sa.String(length=20), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('was_validated', sa.Boolean(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('user_feedback_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_content_cache', schema=None) as batch_op:
        batch_op.create_index('idx_content_type_hash', ['content_type', 'input_hash'], unique=False)
        batch_op.create_index('idx_hit_count', ['hit_count'], unique=False)
        batch_op.create_index('idx_provider_created', ['provider_used', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_content_cache_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_content_cache_input_hash'), ['input_hash'], unique=True)

    op.create_table('user_practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('skill_focus', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('user_answers', sa.JSON(), nullable=False),
    sa.Column('correct_answers', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('accuracy_percentage', sa.Float(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('question_feedback', sa.JSON(), nullable=True),
    sa.Column('strengths_identified', sa.JSON(), nullable=True),
    sa.Column('areas_for_improvement', sa.JSON(), nullable=True),
    sa.Column('next_steps', sa.JSON(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers_count', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('mastery_gain', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_practice_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_user_session_type', ['user_id', 'session_type', 'completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_practice_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_assessment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('skill_area', sa.String(length=50), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('user_answers', sa.JSON(), nullable=False),
    sa.Column('correct_answers', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('proficiency_level', sa.String(length=20), nullable=True),
    sa.Column('skill_breakdown', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('detailed_evaluation', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['proficiency_assessments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_assessment_history', schema=None) as batch_op:
        batch_op.create_index('idx_user_type_date', ['user_id', 'assessment_type', 'completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_assessment_history_user_id'), ['user_id'], unique=False)

    op.create_table('user_conversation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('conversation_type', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('scenario', sa.String(length=200), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('user_message_count', sa.Integer(), nullable=True),
    sa.Column('grammar_corrections', sa.JSON(), nullable=True),
    sa.Column('vocabulary_used', sa.JSON(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('coherence_score', sa.Float(), nullable=True),
    sa.Column('skills_practiced', sa.JSON(), nullable=True),
    sa.Column('learning_points', sa.JSON(), nullable=True),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True),
    sa.Column('response_times', sa.JSON(), nullable=True),
    sa.Column('avg_response_time_seconds', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('vocabulary_added', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_conversation_history', schema=None) as batch_op:
        batch_op.create_index('idx_user_conv_type', ['user_id', 'conversation_type', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_conversation_history_user_id'), ['user_id'], unique=False)

    op.create_table('user_lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('lesson_title', sa.String(length=200), nullable=False),
    sa.Column('lesson_content', sa.JSON(), nullable=True),
    sa.Column('lesson_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('notes_taken', sa.Text(), nullable=True),
    sa.Column('bookmarks', sa.JSON(), nullable=True),
    sa.Column('questions_asked', sa.JSON(), nullable=True),
    sa.Column('comprehension_score', sa.Float(), nullable=True),
    sa.Column('quiz_results', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('key_takeaways', sa.JSON(), nullable=True),
    sa.Column('personalized_insights', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('revisit_count', sa.Integer(), nullable=True),
    sa.Column('helpful_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.create_index('idx_user_chapter', ['user_id', 'chapter_id'], unique=False)
        batch_op.create_index('idx_user_path_status', ['user_id', 'learning_path_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lesson_progress_user_id'), ['user_id'], unique=False)

    op.create_table('user_activity_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_title', sa.String(length=200), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('user_responses', sa.JSON(), nullable=False),
    sa.Column('correct_answers', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('item_feedback', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('items_completed', sa.Integer(), nullable=True),
    sa.Column('items_correct', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('badges_earned', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activity_completions', schema=None) as batch_op:
        batch_op.create_index('idx_user_activity', ['user_id', 'activity_id'], unique=False)
        batch_op.create_index('idx_user_type_completed', ['user_id', 'activity_type', 'completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_completions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_completions_user_id'))
        batch_op.drop_index('idx_user_type_completed')
        batch_op.drop_index('idx_user_activity')

    op.drop_table('user_activity_completions')
    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_lesson_progress_user_id'))
        batch_op.drop_index('idx_user_path_status')
        batch_op.drop_index('idx_user_chapter')

    op.drop_table('user_lesson_progress')
    with op.batch_alter_table('user_conversation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_conversation_history_user_id'))
        batch_op.drop_index('idx_user_conv_type')

    op.drop_table('user_conversation_history')
    with op.batch_alter_table('user_assessment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_assessment_history_user_id'))
        batch_op.drop_index('idx_user_type_date')

    op.drop_table('user_assessment_history')
    with op.batch_alter_table('user_practice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_practice_sessions_user_id'))
        batch_op.drop_index('idx_user_session_type')

    op.drop_table('user_practice_sessions')
    with op.batch_alter_table('ai_content_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_content_cache_input_hash'))
        batch_op.drop_index(batch_op.f('ix_ai_content_cache_content_type'))
        batch_op.drop_index('idx_provider_created')
        batch_op.drop_index('idx_hit_count')
        batch_op.drop_index('idx_content_type_hash')

    op.drop_table('ai_content_cache')
    # ### end Alembic commands ###
