"""Phase 3: Learning nodes and skill profiles

Revision ID: 97731b707dfa
Revises: 04d79400632d
Create Date: 2025-10-19 23:35:46.316324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97731b707dfa'
down_revision = '04d79400632d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase3_skill_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sub_skills', sa.JSON(), nullable=True),
    sa.Column('assessment_criteria', sa.JSON(), nullable=True),
    sa.Column('mastery_thresholds', sa.JSON(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name')
    )
    op.create_table('phase3_curriculum_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('level_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vocabulary_range_min', sa.Integer(), nullable=True),
    sa.Column('vocabulary_range_max', sa.Integer(), nullable=True),
    sa.Column('grammar_concepts', sa.JSON(), nullable=True),
    sa.Column('functional_skills', sa.JSON(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('prerequisite_level_id', sa.Integer(), nullable=True),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prerequisite_level_id'], ['phase3_curriculum_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cefr_level')
    )
    op.create_table('phase3_user_skill_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listening_level', sa.Float(), nullable=True),
    sa.Column('speaking_level', sa.Float(), nullable=True),
    sa.Column('reading_level', sa.Float(), nullable=True),
    sa.Column('writing_level', sa.Float(), nullable=True),
    sa.Column('vocabulary_level', sa.Float(), nullable=True),
    sa.Column('grammar_level', sa.Float(), nullable=True),
    sa.Column('overall_level', sa.Float(), nullable=True),
    sa.Column('listening_trend', sa.String(length=20), nullable=True),
    sa.Column('speaking_trend', sa.String(length=20), nullable=True),
    sa.Column('reading_trend', sa.String(length=20), nullable=True),
    sa.Column('writing_trend', sa.String(length=20), nullable=True),
    sa.Column('vocabulary_trend', sa.String(length=20), nullable=True),
    sa.Column('grammar_trend', sa.String(length=20), nullable=True),
    sa.Column('weak_areas', sa.JSON(), nullable=True),
    sa.Column('strong_areas', sa.JSON(), nullable=True),
    sa.Column('focus_area', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('phase3_learning_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('curriculum_level_id', sa.Integer(), nullable=False),
    sa.Column('skill_domain_id', sa.Integer(), nullable=False),
    sa.Column('concept_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('prerequisite_node_ids', sa.JSON(), nullable=True),
    sa.Column('activity_templates', sa.JSON(), nullable=True),
    sa.Column('difficulty_min', sa.Float(), nullable=True),
    sa.Column('difficulty_max', sa.Float(), nullable=True),
    sa.Column('recommended_difficulty', sa.Float(), nullable=True),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('mastery_threshold', sa.Float(), nullable=True),
    sa.Column('vocabulary_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_level_id'], ['phase3_curriculum_levels.id'], ),
    sa.ForeignKeyConstraint(['skill_domain_id'], ['phase3_skill_domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('phase3_user_learning_node_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_node_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('mastery_level', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('total_time_minutes', sa.Integer(), nullable=True),
    sa.Column('first_attempt_date', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('mastery_date', sa.DateTime(), nullable=True),
    sa.Column('struggle_indicators', sa.JSON(), nullable=True),
    sa.Column('common_errors', sa.JSON(), nullable=True),
    sa.Column('hint_count', sa.Integer(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_node_id'], ['phase3_learning_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phase3_user_learning_node_progress')
    op.drop_table('phase3_learning_nodes')
    op.drop_table('phase3_user_skill_profiles')
    op.drop_table('phase3_curriculum_levels')
    op.drop_table('phase3_skill_domains')
    # ### end Alembic commands ###
