"""Add enrollment_data field to users table

Revision ID: a160ccf443f9
Revises: dd2d5dbb8eb1
Create Date: 2025-09-23 18:45:58.172283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a160ccf443f9'
down_revision = 'dd2d5dbb8eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('enrollment_data')

    # ### end Alembic commands ###
