"""Add Phase 9 gamification models

Revision ID: b31733d12644
Revises: 97731b707dfa
Create Date: 2025-10-21 15:39:46.756162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b31733d12644'
down_revision = '97731b707dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamification_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement_key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('badge_image', sa.String(length=200), nullable=True),
    sa.Column('unlock_criteria', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('points_value', sa.Integer(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=True),
    sa.Column('is_repeatable', sa.Boolean(), nullable=True),
    sa.Column('prerequisite_achievement', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('achievement_key')
    )
    with op.batch_alter_table('gamification_achievements', schema=None) as batch_op:
        batch_op.create_index('idx_achievement_category', ['category', 'subcategory'], unique=False)
        batch_op.create_index('idx_achievement_rarity', ['rarity', 'is_active'], unique=False)

    op.create_table('gamification_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_date', sa.Date(), nullable=False),
    sa.Column('challenge_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_metric', sa.String(length=100), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=True),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.Column('bonus_multiplier', sa.Float(), nullable=True),
    sa.Column('badge_reward', sa.String(length=100), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_streak_bonus', sa.Boolean(), nullable=True),
    sa.Column('skill_focus', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('weak_areas_targeted', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_date', 'challenge_type', name='uq_user_daily_challenge')
    )
    with op.batch_alter_table('gamification_challenges', schema=None) as batch_op:
        batch_op.create_index('idx_challenge_active', ['user_id', 'is_completed', 'expires_at'], unique=False)
        batch_op.create_index('idx_user_challenge_date', ['user_id', 'challenge_date'], unique=False)

    op.create_table('gamification_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('streak_start_date', sa.Date(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak_start', sa.Date(), nullable=True),
    sa.Column('longest_streak_end', sa.Date(), nullable=True),
    sa.Column('freeze_count', sa.Integer(), nullable=True),
    sa.Column('max_freezes', sa.Integer(), nullable=True),
    sa.Column('freezes_used', sa.Integer(), nullable=True),
    sa.Column('last_freeze_earned', sa.Date(), nullable=True),
    sa.Column('is_recovery_available', sa.Boolean(), nullable=True),
    sa.Column('recovery_challenge_completed', sa.Boolean(), nullable=True),
    sa.Column('recovery_expires_at', sa.DateTime(), nullable=True),
    sa.Column('milestone_7_reached', sa.Boolean(), nullable=True),
    sa.Column('milestone_30_reached', sa.Boolean(), nullable=True),
    sa.Column('milestone_100_reached', sa.Boolean(), nullable=True),
    sa.Column('milestone_365_reached', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('gamification_streaks', schema=None) as batch_op:
        batch_op.create_index('idx_user_streak', ['user_id', 'current_streak'], unique=False)

    op.create_table('leaderboard_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('time_period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('activities_completed', sa.Integer(), nullable=True),
    sa.Column('study_time_minutes', sa.Integer(), nullable=True),
    sa.Column('accuracy_percentage', sa.Float(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'time_period', 'period_start', name='uq_leaderboard_entry')
    )
    with op.batch_alter_table('leaderboard_entries', schema=None) as batch_op:
        batch_op.create_index('idx_leaderboard_category_period', ['category', 'time_period', 'period_start'], unique=False)
        batch_op.create_index('idx_leaderboard_ranking', ['category', 'time_period', 'score', 'rank'], unique=False)

    op.create_table('progress_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('milestone_type', sa.String(length=50), nullable=False),
    sa.Column('milestone_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('achieved_value', sa.Integer(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('badge_awarded', sa.String(length=100), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('reached_at', sa.DateTime(), nullable=False),
    sa.Column('celebrated', sa.Boolean(), nullable=True),
    sa.Column('related_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_milestones', schema=None) as batch_op:
        batch_op.create_index('idx_milestone_key', ['user_id', 'milestone_key'], unique=False)
        batch_op.create_index('idx_user_milestone', ['user_id', 'milestone_type'], unique=False)

    op.create_table('shared_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('shared_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_achievements', schema=None) as batch_op:
        batch_op.create_index('idx_shared_feed', ['visibility', 'shared_at'], unique=False)
        batch_op.create_index('idx_user_shares', ['user_id', 'shared_at'], unique=False)

    op.create_table('social_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connected_user_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('matched_by_ai', sa.Boolean(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('common_interests', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connected_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'connected_user_id', name='uq_user_connection')
    )
    with op.batch_alter_table('social_connections', schema=None) as batch_op:
        batch_op.create_index('idx_connection_pair', ['user_id', 'connected_user_id'], unique=False)
        batch_op.create_index('idx_user_connections', ['user_id', 'status'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.Column('progress_when_unlocked', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('unlock_count', sa.Integer(), nullable=True),
    sa.Column('last_unlock_at', sa.DateTime(), nullable=True),
    sa.Column('is_showcased', sa.Boolean(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index('idx_user_achievement', ['user_id', 'achievement_id'], unique=False)
        batch_op.create_index('idx_user_showcased', ['user_id', 'is_showcased'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index('idx_user_showcased')
        batch_op.drop_index('idx_user_achievement')

    op.drop_table('user_achievements')
    with op.batch_alter_table('social_connections', schema=None) as batch_op:
        batch_op.drop_index('idx_user_connections')
        batch_op.drop_index('idx_connection_pair')

    op.drop_table('social_connections')
    with op.batch_alter_table('shared_achievements', schema=None) as batch_op:
        batch_op.drop_index('idx_user_shares')
        batch_op.drop_index('idx_shared_feed')

    op.drop_table('shared_achievements')
    with op.batch_alter_table('progress_milestones', schema=None) as batch_op:
        batch_op.drop_index('idx_user_milestone')
        batch_op.drop_index('idx_milestone_key')

    op.drop_table('progress_milestones')
    with op.batch_alter_table('leaderboard_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_leaderboard_ranking')
        batch_op.drop_index('idx_leaderboard_category_period')

    op.drop_table('leaderboard_entries')
    with op.batch_alter_table('gamification_streaks', schema=None) as batch_op:
        batch_op.drop_index('idx_user_streak')

    op.drop_table('gamification_streaks')
    with op.batch_alter_table('gamification_challenges', schema=None) as batch_op:
        batch_op.drop_index('idx_user_challenge_date')
        batch_op.drop_index('idx_challenge_active')

    op.drop_table('gamification_challenges')
    with op.batch_alter_table('gamification_achievements', schema=None) as batch_op:
        batch_op.drop_index('idx_achievement_rarity')
        batch_op.drop_index('idx_achievement_category')

    op.drop_table('gamification_achievements')
    # ### end Alembic commands ###
