"""Add activity fields to LearningSession model

Revision ID: b4d09671e539
Revises: 135f40a5c2cc
Create Date: 2025-10-09 15:09:33.213098

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4d09671e539"
down_revision = "135f40a5c2cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("learning_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("activity_type", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(sa.Column("topic", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("level", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("score", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("points_earned", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("time_spent_minutes", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("started_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("completed_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("learning_sessions", schema=None) as batch_op:
        batch_op.drop_column("completed_at")
        batch_op.drop_column("started_at")
        batch_op.drop_column("time_spent_minutes")
        batch_op.drop_column("points_earned")
        batch_op.drop_column("score")
        batch_op.drop_column("level")
        batch_op.drop_column("topic")
        batch_op.drop_column("activity_type")

    # ### end Alembic commands ###
