"""Add longest_streak to Profile model

Revision ID: c3775b52af82
Revises: 4e9b68a25330
Create Date: 2025-09-23 16:42:07.846218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3775b52af82'
down_revision = '4e9b68a25330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longest_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('longest_streak')

    # ### end Alembic commands ###
