"""add_missing_fields_to_proficiency_assessments

Revision ID: d1cf010eeb2a
Revises: a160ccf443f9
Create Date: 2025-09-24 14:40:15.665551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cf010eeb2a'
down_revision = 'a160ccf443f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proficiency_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('evaluation_results', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('skill_breakdown', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proficiency_assessments', schema=None) as batch_op:
        batch_op.drop_column('started_at')
        batch_op.drop_column('status')
        batch_op.drop_column('max_score')
        batch_op.drop_column('score')
        batch_op.drop_column('skill_breakdown')
        batch_op.drop_column('evaluation_results')
        batch_op.drop_column('questions_data')

    # ### end Alembic commands ###
