"""Fix activity model field names path_id to learning_path_id

Revision ID: dd2d5dbb8eb1
Revises: 1b65a59f882b
Create Date: 2025-09-23 18:19:52.403960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2d5dbb8eb1'
down_revision = '1b65a59f882b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_path_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('activities_path_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'learning_paths', ['learning_path_id'], ['id'])
        batch_op.drop_column('path_id')

    with op.batch_alter_table('user_activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_path_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'learning_paths', ['learning_path_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('learning_path_id')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activities_path_id_fkey'), 'learning_paths', ['path_id'], ['id'])
        batch_op.drop_column('learning_path_id')

    # ### end Alembic commands ###
